# Dependencies
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink: /:slug.html

# Setup
title: Artem Konovalov â€“ Software Engineer
tagline: |
  posts on JVM based languages, concurrent programming, 
  functional programming and stuff
description: |
  This website is a personal blog. Mainly there are
  posts about java, but you can find ones on other topics.
url:              https://izebit.ru
baseurl:          /

author:
  name: 'Artem Konovalov'
  email: izebit@gmail.com

logo: /assets/logos/photos/main-thumbnail.jpg

webmaster_verifications:
  google: MGhCSoTWiTCeUdZ_2tNyZZ5dmg8Yn18pjFuo9HhksIw
  yandex: 34c428376cb827b4

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

